name = "pumpos-web"
compatibility_date = "2026-06-24"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"

[env.preview]
workers_dev = true

[env.preview.assets]
directory = "./dist"
not_found_handling = "single-page-application"
