/**
 * Business Event Catalog (Handbook Vol. 4).
 *
 * Every meaningful business action emits one of these events. Capabilities may
 * also define local event-type constants, but anything consumed across
 * bounded contexts belongs here. The catalog grows per implementation phase;
 * never rename or remove an existing event type (events are permanent).
 */
export const BusinessEvents = {
  // --- Identity & Station Setup ---
  ORGANIZATION_CREATED: 'ORGANIZATION_CREATED',
  STATION_CREATED: 'STATION_CREATED',
  STATION_UPDATED: 'STATION_UPDATED',
  USER_CREATED: 'USER_CREATED',
  PRODUCT_CREATED: 'PRODUCT_CREATED',
  PRODUCT_UPDATED: 'PRODUCT_UPDATED',
  PRICE_CHANGED: 'PRICE_CHANGED',
  PAYMENT_TERMINAL_REGISTERED: 'PAYMENT_TERMINAL_REGISTERED',
  PAYMENT_TERMINAL_UPDATED: 'PAYMENT_TERMINAL_UPDATED',
  TANK_CREATED: 'TANK_CREATED',
  TANK_UPDATED: 'TANK_UPDATED',
  TANK_DELETED: 'TANK_DELETED',
  DISPENSER_CREATED: 'DISPENSER_CREATED',
  DISPENSER_UPDATED: 'DISPENSER_UPDATED',
  DISPENSER_DELETED: 'DISPENSER_DELETED',
  NOZZLE_CREATED: 'NOZZLE_CREATED',
  NOZZLE_UPDATED: 'NOZZLE_UPDATED',
  NOZZLE_DELETED: 'NOZZLE_DELETED',
  SHIFT_TEMPLATE_CREATED: 'SHIFT_TEMPLATE_CREATED',
  SHIFT_TEMPLATE_UPDATED: 'SHIFT_TEMPLATE_UPDATED',
  SHIFT_TEMPLATE_DELETED: 'SHIFT_TEMPLATE_DELETED',
  USER_UPDATED: 'USER_UPDATED',
  ONBOARDING_COMPLETED: 'ONBOARDING_COMPLETED',

  // --- Station Operations (Shift + Business Day) ---
  BUSINESS_DAY_OPENED: 'BUSINESS_DAY_OPENED',
  BUSINESS_DAY_CLOSED: 'BUSINESS_DAY_CLOSED',
  SHIFT_OPENED: 'SHIFT_OPENED',
  SHIFT_CLOSED: 'SHIFT_CLOSED',
  SHIFT_REOPENED: 'SHIFT_REOPENED',
  SHIFT_LOCKED: 'SHIFT_LOCKED',
  ATTENDANT_ASSIGNED: 'ATTENDANT_ASSIGNED',
  NOZZLE_READING_RECORDED: 'NOZZLE_READING_RECORDED',
  CASH_DECLARED: 'CASH_DECLARED',
  HANDOVER_RECORDED: 'HANDOVER_RECORDED',
  DSSR_GENERATED: 'DSSR_GENERATED',

  // --- Retail ---
  FUEL_SALE_RECORDED: 'FUEL_SALE_RECORDED',
  RETAIL_SALE_CREATED: 'RETAIL_SALE_CREATED',
  RETAIL_SALE_VOIDED: 'RETAIL_SALE_VOIDED',
  RETAIL_SALE_RETURNED: 'RETAIL_SALE_RETURNED',
  DISCOUNT_APPLIED: 'DISCOUNT_APPLIED',

  // --- Inventory ---
  STOCK_MOVEMENT_RECORDED: 'STOCK_MOVEMENT_RECORDED',
  FUEL_RECEIVED: 'FUEL_RECEIVED',
  TANK_DIP_RECORDED: 'TANK_DIP_RECORDED',
  TANK_TRANSFER_COMPLETED: 'TANK_TRANSFER_COMPLETED',
  INVENTORY_ADJUSTED: 'INVENTORY_ADJUSTED',
  PHYSICAL_COUNT_COMPLETED: 'PHYSICAL_COUNT_COMPLETED',
  VARIANCE_RECORDED: 'VARIANCE_RECORDED',

  // --- Purchasing ---
  SUPPLIER_CREATED: 'SUPPLIER_CREATED',
  SUPPLIER_UPDATED: 'SUPPLIER_UPDATED',
  PURCHASE_CREATED: 'PURCHASE_CREATED',
  PURCHASE_APPROVED: 'PURCHASE_APPROVED',
  GOODS_RECEIVED: 'GOODS_RECEIVED',
  SUPPLIER_INVOICE_CREATED: 'SUPPLIER_INVOICE_CREATED',
  SUPPLIER_PAID: 'SUPPLIER_PAID',

  // --- CRM ---
  CUSTOMER_CREATED: 'CUSTOMER_CREATED',
  CUSTOMER_UPDATED: 'CUSTOMER_UPDATED',
  VEHICLE_ADDED: 'VEHICLE_ADDED',
  VEHICLE_UPDATED: 'VEHICLE_UPDATED',
  VEHICLE_REMOVED: 'VEHICLE_REMOVED',
  CREDIT_LIMIT_CHANGED: 'CREDIT_LIMIT_CHANGED',
  CREDIT_SALE_CREATED: 'CREDIT_SALE_CREATED',
  CREDIT_PAYMENT_RECEIVED: 'CREDIT_PAYMENT_RECEIVED',

  // --- Finance ---
  EXPENSE_RECORDED: 'EXPENSE_RECORDED',
  EXPENSE_VOIDED: 'EXPENSE_VOIDED',
  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
  PAYMENT_MADE: 'PAYMENT_MADE',
} as const;

export type BusinessEventType = (typeof BusinessEvents)[keyof typeof BusinessEvents];
