import {
  AlertCircle,
  AlertTriangle,
  ArrowDown,
  ArrowDownRight,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  Ban,
  Banknote,
  BarChart3,
  Bell,
  BookOpen,
  Boxes,
  Building,
  Building2,
  Calculator,
  Calendar,
  CalendarRange,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clock,
  ClipboardCheck,
  Clock3,
  Command,
  Copy,
  CornerDownLeft,
  CreditCard,
  Database,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  Filter,
  Fuel,
  Gauge,
  Globe,
  GripVertical,
  HelpCircle,
  Info,
  KeyRound,
  Layers,
  LayoutDashboard,
  Lock,
  LogOut,
  Menu,
  Minus,
  Package,
  Pencil,
  Percent,
  Play,
  Plus,
  Printer,
  Receipt,
  RefreshCw,
  Save,
  Scale,
  Search,
  Settings,
  Shield,
  ShoppingBag,
  ShoppingCart,
  Sliders,
  Tag,
  Tags,
  Trash2,
  TrendingDown,
  TrendingUp,
  Truck,
  Unlock,
  Upload,
  User,
  Users,
  Wallet,
  X,
  XCircle,
  Zap,
  type LucideIcon,
} from 'lucide-react';

/**
 * Canonical registry of icons used across PumpOS.
 *
 * Maps standard action names and operational domain concepts
 * to their underlying Lucide SVG components.
 */
export const ICON_REGISTRY = {
  // Actions & Controls
  plus: Plus,
  add: Plus,
  minus: Minus,
  check: Check,
  'check-circle': CheckCircle2,
  x: X,
  close: X,
  'x-circle': XCircle,
  search: Search,
  pencil: Pencil,
  edit: Pencil,
  trash: Trash2,
  delete: Trash2,
  save: Save,
  download: Download,
  upload: Upload,
  copy: Copy,
  'external-link': ExternalLink,
  refresh: RefreshCw,
  filter: Filter,
  'grip-vertical': GripVertical,
  ban: Ban,
  'corner-down-left': CornerDownLeft,
  play: Play,
  eye: Eye,
  'eye-off': EyeOff,
  sliders: Sliders,
  menu: Menu,
  bell: Bell,
  command: Command,

  // Navigation & Directional
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'arrow-left-right': ArrowLeftRight,
  'arrow-up-right': ArrowUpRight,
  'arrow-down-right': ArrowDownRight,

  // Domain & Fuel Operations
  dashboard: LayoutDashboard,
  shift: Clock,
  shifts: Clock,
  fuel: Fuel,
  dispenser: Fuel,
  nozzle: Fuel,
  gauge: Gauge,
  zap: Zap,
  tank: Database,
  database: Database,
  cash: Banknote,
  banknote: Banknote,
  card: CreditCard,
  'credit-card': CreditCard,
  terminal: CreditCard,
  wallet: Wallet,
  upi: Wallet,
  accounts: Wallet,
  receipt: Receipt,
  expense: Receipt,
  expenses: Receipt,
  income: TrendingUp,
  tax: Percent,
  percent: Percent,
  pricing: Tag,
  calendar: Calendar,
  'calendar-range': CalendarRange,
  clock: Clock,
  clock3: Clock3,
  calculator: Calculator,
  cart: ShoppingCart,
  'shopping-cart': ShoppingCart,
  purchase: ShoppingCart,
  purchases: ShoppingCart,
  'shopping-bag': ShoppingBag,
  bag: ShoppingBag,
  package: Package,
  product: Package,
  products: Package,
  boxes: Boxes,
  inventory: Boxes,
  'clipboard-check': ClipboardCheck,
  'stock-count': ClipboardCheck,
  scale: Scale,
  reconcile: Scale,
  layers: Layers,
  'design-system': Layers,
  truck: Truck,
  supplier: Truck,
  user: User,
  customer: User,
  users: Users,
  customers: Users,
  team: Users,
  station: Building2,
  building: Building2,
  organization: Building,
  company: Building,
  onboarding: Settings,
  ledger: BookOpen,
  'book-open': BookOpen,
  'file-text': FileText,
  invoice: FileText,
  invoices: FileText,
  report: FileText,
  reports: FileText,
  analytics: BarChart3,
  chart: BarChart3,
  'bar-chart': BarChart3,
  sales: TrendingUp,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  lock: Lock,
  unlock: Unlock,
  key: KeyRound,
  'alert-triangle': AlertTriangle,
  warning: AlertTriangle,
  'alert-circle': AlertCircle,
  error: AlertCircle,
  info: Info,
  help: HelpCircle,
  'help-circle': HelpCircle,
  tag: Tag,
  tags: Tags,
  globe: Globe,
  printer: Printer,
  settings: Settings,
  shield: Shield,
  logout: LogOut,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICON_REGISTRY;
