import React from 'react';
import { Document, Page, View, Text } from '@react-pdf/renderer';
import {
  C, s, TableView, Kpi, LetterheadBand, inr, inr0, fmtDateTime,
  type Col, type Cell, type Letterhead,
} from './shiftSummaryDoc.js';

export interface LedgerDocRow {
  dateLabel: string;
  particulars: string;
  debit: number;
  credit: number;
  balance: number;
}

export interface LedgerDocProps {
  /** Document title, e.g. "CUSTOMER LEDGER". */
  title: string;
  /** Account name / description shown in the sub-line. */
  entityName: string;
  periodLabel: string;
  debitLabel: string;
  creditLabel: string;
  balanceLabel: string;
  /** Chronological (oldest→newest) rows with running balance. */
  rows: LedgerDocRow[];
  totals: { debit: number; credit: number; balance: number };
  stationName?: string;
  letterhead?: Letterhead;
  generatedAt?: string;
}

/**
 * Vector PDF statement for any ledger entity (customer, supplier, cash, bank,
 * owner) — reuses the shared Phase-R react-pdf kit (letterhead, KPI tiles,
 * generic two-column-style table). Rows arrive already resolved + balanced by
 * `computeLedgerRows` so the PDF matches the on-screen `<LedgerView>` exactly.
 */
export const LedgerDoc: React.FC<LedgerDocProps> = ({
  title,
  entityName,
  periodLabel,
  debitLabel,
  creditLabel,
  balanceLabel,
  rows,
  totals,
  stationName,
  letterhead,
  generatedAt,
}) => {
  const cols: Col[] = [
    { header: 'Date', flex: 1.3, strong: true },
    { header: 'Particulars', flex: 2.8 },
    { header: debitLabel, flex: 1.4, align: 'right', mono: true },
    { header: creditLabel, flex: 1.4, align: 'right', mono: true },
    { header: balanceLabel, flex: 1.5, align: 'right', mono: true, strong: true },
  ];
  const cellRows: Cell[][] = rows.map((r) => [
    { text: r.dateLabel },
    { text: r.particulars },
    { text: r.debit ? inr(r.debit) : '' },
    { text: r.credit ? inr(r.credit) : '', color: r.credit ? C.success : undefined },
    { text: inr(r.balance) },
  ]);
  const totalRow: Cell[] = [
    { text: 'TOTALS' },
    { text: '' },
    { text: inr(totals.debit) },
    { text: inr(totals.credit), color: C.success },
    { text: inr(totals.balance), color: C.ink },
  ];

  return (
    <Document>
      <Page size="A4" style={s.page}>
        <LetterheadBand title={title} stationName={stationName} letterhead={letterhead} />
        <Text style={s.sub}>
          {entityName} {'\u2022'} {periodLabel}
          {generatedAt ? ` \u2022 Generated ${fmtDateTime(generatedAt)}` : ''}
        </Text>

        <View style={s.kpiRow}>
          <Kpi l={debitLabel} v={inr0(totals.debit)} />
          <Kpi l={creditLabel} v={inr0(totals.credit)} c={C.success} />
          <Kpi l={balanceLabel} v={inr0(totals.balance)} c={totals.balance < 0 ? C.danger : C.ink} />
        </View>

        <Text style={s.h2}>STATEMENT OF ACCOUNT</Text>
        {rows.length === 0 ? (
          <Text style={{ fontSize: 9, color: C.muted, marginTop: 4 }}>No transactions in this period.</Text>
        ) : (
          <TableView columns={cols} rows={cellRows} total={totalRow} />
        )}

        <View style={s.foot} fixed>
          <Text>Generated by PumpOS</Text>
          <Text render={({ pageNumber, totalPages }) => `Page ${pageNumber} / ${totalPages}`} />
        </View>
      </Page>
    </Document>
  );
};
